version: '3.4'

services:
  otus.ha.sn.web.api:
    image: ${DOCKER_REGISTRY-}otushasnwebapi
    container_name: web_api_application
    hostname: web_api
    depends_on: 
      - db
    ports:
      - "5080:80"
      - "5443:443"
    build:
      context: .
      dockerfile: ./src/Api/OTUS.HA.SN.Web.Api/Dockerfile
  db:
    image: postgres:15.4
    shm_size: 1gb
    command:
      - "postgres"
      - "-c"
      - "max_connections=10000"
      - "-c"
      - "shared_buffers=256MB"
    container_name: postgres_db
    hostname: postgres_db
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./deploy/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./deploy/user_data.copy:/docker-entrypoint-initdb.d/user_data.copy
