version: '3.4'

services:
  otus.ha.sn.web.api:
    image: ${DOCKER_REGISTRY-}otushasnwebapi
    container_name: web_api_application
    hostname: web_api
    networks:
      - social_network_common
    depends_on: 
      - db-master
      - db-slave-1
      - cache
    ports:
      - "5080:80"
    build:
      context: .
      dockerfile: ./src/Api/OTUS.HA.SN.Web.Api/Dockerfile
  db-master:
    image: postgres:15.4
    shm_size: 1gb
    container_name: postgres_db_master
    hostname: postgres_db_master
    networks:
      - social_network_common
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ${PG_MASTER_DATA_PATH}:/var/lib/postgresql/data
      - ./deploy/psql/master/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./deploy/user_data.copy:/docker-entrypoint-initdb.d/user_data.copy
      - ./deploy/psql/master/postgresql.conf:/tmp/postgresql.conf
      - ./deploy/psql/master/pg_hba.conf:/tmp/pg_hba.conf
  db-slave-1:
    image: postgres:15.4
    shm_size: 1gb
    container_name: postgres_db_slave_1
    hostname: postgres_db_slave_1
    networks:
      - social_network_common
    depends_on: 
      - db-master
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
     - ${PG_SLAVE_1_DATA_PATH}:/var/lib/postgresql/data
     - ./deploy/psql/slave/init_slave.sh:/docker-entrypoint-initdb.d/init_slave.sh
  db-slave-2:
    image: postgres:15.4
    shm_size: 1gb
    container_name: postgres_db_slave_2
    hostname: postgres_db_slave_2
    networks:
      - social_network_common
    depends_on: 
      - db-master
    environment:
      POSTGRES_PASSWORD: password
    volumes:
     - ${PG_SLAVE_2_DATA_PATH}:/var/lib/postgresql/data
     - ./deploy/psql/slave/init_slave.sh:/docker-entrypoint-initdb.d/init_slave.sh
  cache:
    image: redis:7.2.0
    container_name: redis_cache
    hostname: redis_cache
    depends_on: 
      - db-master
    networks:
      - social_network_common
    ports:
      - "6379:6379"
  citus_master:
    container_name: "citus_db_master"
    hostname: citus_db_master
    image: "citusdata/citus:postgres_15"
    ports: ["${COORDINATOR_EXTERNAL_PORT:-35432}:5432"]
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "password"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
    volumes:
     - ${CITUS_MASTER_DATA_PATH}:/var/lib/postgresql/data
     - ./deploy/citus/master/init.sh:/docker-entrypoint-initdb.d/init.sh
  citus_worker:
    image: "citusdata/citus:postgres_15"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [citus_manager]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
  citus_manager:
    container_name: "citus_db_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [citus_master]
    environment: &AUTH
      CITUS_HOST: citus_db_master
volumes:
  healthcheck-volume:
networks:
  social_network_common:
    name: social_network_common
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
  
